#====================================================================
01 gsyn:
	dc_shell-xg-t -f do_syn.scr |tee syn_dc_shell.log

#====================================================================
90 clean:
	rm -rf *.log
	rm -rf *.ddc
	rm -rf *.vg
	rm -rf *.sdf
	rm -rf *.pvl
	rm -rf *.syn
	rm -rf *.mr
	rm -rf *.svf
